In [1]:
import pandas as pd

In [140]:
cols_name = []
with open('cols_name.txt', 'r') as file:
    cols = file.read()

In [141]:
cols_name = cols.split(",")
for i in range(0, len(cols_name)):
    cols_name[i] = cols_name[i][1:len(cols_name[i])-1]

In [142]:
df = pd.read_csv('Fund Comparison.csv', names=cols_name)

In [149]:
for i in range(len(df.columns)):
    df.iloc[:, i].replace(["-", "-%"], None, inplace=True)
    df.iloc[:, i].replace("ไม่มี", "No", inplace=True)

In [151]:
df.iloc[:, 20:].head(15)

,max_draw_1y,max_draw_3y,max_draw_5y,max_draw_10y,std_1y,std_3y,std_5y,std_10y,as_of,stock_perc,...,max_frontend,actual_fe_fee,max_backend,actual_be_fee,max_mm_fee,actual_mm_fee,max_total_fee,actual_total_fee,min_sub,min_redemp
0,None,None,None,None,0.05,0.04,0.05,0.06,06/2023,None,...,0,0,0,0,0.92769,0.31,4.28,0.43,None,None
1,None,None,None,None,0.05,None,None,None,06/2023,None,...,0,0,0,0,1.07,0.31,4.28,0.43,None,None
2,-0.1291,-0.3179,-0.3179,-0.3221,14.07,15.52,17.2,15,06/2023,None,...,1.07,1.07,1.07,0.27,1.68525,1.07,6.42,1.22,None,None
3,None,-0.0009,-0.0009,-0.0009,0.13,0.09,0.08,0.11,06/2023,None,...,0,0,0,0,0.92769,0.31,4.28,0.45,None,None
4,-0.0075,-0.0233,-0.0723,-0.0723,2.7,3,4.06,4.7,08/2019,0,...,0.107,0.0535,No,0,0.1605,0.107,4.28,0.1391,1000000,None
5,-0.0042,-0.021,-0.0307,-0.0399,2.05,2.26,2.8,3.71,07/2019,0,...,No,0,No,0,0.8025,0.4815,4.28,0.5136,1000000,None
6,None,None,None,None,None,None,None,None,06/2023,97.92,...,None,None,None,None,None,None,None,None,None,None
7,None,None,None,None,None,None,None,None,06/2023,97.92,...,None,None,None,None,None,None,None,None,None,None
8,-0.1092,-0.1092,None,None,10.74,13.9,None,None,06/2023,97.92,...,2.14,0.21,2.14,0,2.14,0.52,6.42,0.66,None,None
9,-0.1086,-0.1086,-0.3999,-0.4067,10.74,13.48,17.39,15.48,06/2023,97.92,...,0.27,0.27,0,0,0.52002,0.52,6.42,0.66,None,None
10,None,None,None,None,None,None,None,None,06/2023,97.92,...,None,None,None,None,None,None,None,None,None,None
11,-0.1092,-0.1092,-0.4005,-0.4077,10.74,13.48,17.38,15.48,06/2023,97.92,...,2.14,0.54,2.14,0,2.675,0.52,6.42,0.66,None,None
12,-0.1061,-0.1128,-0.4943,-0.5393,10.69,13.62,18.62,17.33,06/2023,96.61,...,0,0,0,0,1.1235,0.88,6.42,1.4,None,None
13,-0.0713,-0.2028,-0.2306,-0.3007,5.77,4.23,4.61,4.02,06/2023,None,...,0.54,0,0.54,0,0.842625,0.8,4.28,0.94,None,None
14,-0.1157,-0.1169,None,None,10.76,13.03,None,None,06/2023,98.57,...,1.07,1.07,0.27,0,2.04798,2.05,6.42,2.19,None,None

In [153]:
df.to_csv('cleaned_data.csv')

In [155]:
a = [5,5,87]
for i, b in enumerate(a):
    print(i, b)

0 5
1 5
2 87

In [157]:
pip install requests

Collecting requests
  Obtaining dependency information for requests from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/bc/85/ef25d4ba14c7653c3020a1c6e1a7413e6791ef36a0ac177efa605fc2c737/charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 5.0 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1 (from requests)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Downloading urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 7.7 MB/s eta 0:00:00
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 kB 7.9 MB/s eta 0:00:00
Downloading charset_normalizer-3.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.6/199.6 kB 8.1 MB/s eta 0:00:00
Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 9.2 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.7.22 charset-normalizer-3.2.0 idna-3.4 requests-2.31.0 urllib3-2.0.4
Note: you may need to restart the kernel to use updated packages.

In [161]:
r = requests.get("https://api.sec.or.th/common/ref/product/secu_type")

In [159]:
import requests

In [162]:
r.json()

{'statusCode': 401,
 'message': 'Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API.'}

In [225]:
headers = {
    'Ocp-Apim-Subscription-Key': '98fb5b95961741beba453e85fd95bae9' #fund fact
}
unique_id 
am = requests.get(url="https://api.sec.or.th/FundFactsheet/fund/amc", headers=headers)
fund = requests.get(url="https://api.sec.or.th/FundFactsheet/fund/M1261_2557/policy", headers=headers)

In [227]:
fund.json()

{'last_upd_date': '2023-09-06T05:03:38',
 'policy_desc': 'ตราสารทุน',
 'management_style': 'PN',
 'investment_policy_desc': 'PHA+4oCiIOC4geC4reC4h+C4l+C4uOC4meC5gOC4meC5ieC4meC4peC4h+C4l+C4uOC4meC5g+C4meC4q+C4meC5iOC4p+C4ouC4peC4h+C4l+C4uOC4meC4guC4reC4h+C4geC4reC4h+C4l+C4uOC4mSBDU09QIEZUU0UgQ2hpbmEgQTUwIEVURiAoUk1CKSAo4LiB4Lit4LiH4LiX4Li44LiZ4Lir4Lil4Lix4LiBKSA8YnI+4oCiIOC4geC4reC4h+C4l+C4uOC4meC4m+C5ieC4reC4h+C4geC4seC4meC4hOC4p+C4suC4oeC5gOC4quC4teC5iOC4ouC4h+C4iOC4suC4geC4reC4seC4leC4o+C4suC5geC4peC4geC5gOC4m+C4peC4teC5iOC4ouC4meC5hOC4oeC5iOC4meC5ieC4reC4ouC4geC4p+C5iOC4siA3NSUgIOC4guC4reC4h+C4oeC4ueC4peC4hOC5iOC4suC5gOC4h+C4tOC4meC4peC4h+C4l+C4uOC4meC4leC5iOC4suC4h+C4m+C4o+C4sOC5gOC4l+C4qDwvcD48cD7guJnguYLguKLguJrguLLguKLguIHguK3guIfguJfguLjguJkgQ1NPUCBGVFNFIENoaW5hIEE1MCBFVEYgKFJNQikgICjguIHguK3guIfguJfguLjguJnguKvguKXguLHguIEpPGJyPkJsb29tYmVyZyBUaWNrZXI6IDgyODIyOkhLPGJyPuKAoiDguIHguK3guIfguJfguLjguJnguKvguKXguLHguIHguYDguJvguYfguJnguIHguK3guIfguJfguLjguJnguK3guLXguJfguLXguYDguK3guJ/guJfguLXguYjguIjguJTguJfguLDguYDguJrguLXguKLguJnguIvguLfguYnguK3guILguLLguKLguYPguJnguJXguKXguLLguJTguKvguLjguYnguJnguK7guYjguK3guIfguIHguIcg4LiL4Li24LmI4LiH4Lih4Li14LiZ4LmC4Lii4Lia4Liy4Lii4LiB4Liy4Lij4Lil4LiH4LiX4Li44LiZ4LmD4Lir4LmJ4Lih4Li14Lic4Lil4LiV4Lit4Lia4LmB4LiX4LiZ4LiV4Liy4Lih4LiU4Lix4LiK4LiZ4Li1IOC4q+C4uOC5ieC4meC4iOC4teC4mSBGVFNFIENoaW5hIEE1MDwvcD4='}

In [224]:
df

,proj_id,regis_id,regis_date,cancel_date,proj_name_th,proj_name_en,proj_abbr_name,fund_status,unique_id,permit_us_investment,invest_country_flag,last_upd_date
0,M0000_2553,611_2552,2009-12-30,2010-04-02,กองทุนเปิดเค ตราสารหนี้ 3 เดือน บี,K Fixed Income 3 Months B Fund,KFI3MB,LI,C0000000021,-,3,2023-09-06T05:04:08
1,M0001_2558,MF0013_2558,2015-01-14,2016-01-21,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ต่างประเทศ 1...,K Enhanced Foreign Fixed Income 1 Year AD Fund,KEFF1YAD,LI,C0000000021,-,1,2023-09-06T05:04:08
2,M0003_2558,MF0012_2558,2015-01-14,2015-04-23,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 3 เดือน K,K Enhanced Fixed Income 3 Months K Fund,KEFI3MK,LI,C0000000021,-,2,2023-09-06T05:04:08
3,M0003_2563,-,-,-,กองทุนเปิดเค ตราสารหนี้ต่างประเทศ 6 เดือน HX,K Foreign Fixed Income 6 Months HX Fund,KFF6MHX,EX,C0000000021,-,1,2023-09-06T05:04:08
4,M0004_2555,MF0020_2555,2012-01-18,2012-07-20,กองทุนเปิดเค ตราสารหนี้ 6 เดือน เอเจ,K Fixed Income 6 Months AJ Fund,KFI6MAJ,LI,C0000000021,-,2,2023-09-06T05:04:08
...,...,...,...,...,...,...,...,...,...,...,...,...
1994,M1240_2557,MF0871_2557,2014-12-26,2015-07-08,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 6 เดือน F,K Enhanced Fixed Income 6 Months F Fund,KEFI6MF,LI,C0000000021,-,2,2023-09-06T05:04:08
1995,M1248_2557,-,-,-,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ต่างประเทศ พ...,K Enhanced Foreign Fixed Income Plus 3 Months ...,KEFFP3MA,EX,C0000000021,-,1,2023-09-06T05:04:08
1996,M1261_2557,MF0464_2558,2015-09-08,-,กองทุนเปิดเค ดัชนีหุ้นจีน,K Chinese Equity Index Fund,K-CHX,RG,C0000000021,-,1,2023-09-06T05:04:08
1997,M1262_2557,MF0011_2558,2015-01-14,2015-07-23,กองทุนเปิดเค ตราสารหนี้ 6 เดือน CO,K Fixed Income 6 Months CO Fund,KFI6MCO,LI,C0000000021,-,2,2023-09-06T05:04:08
1998,M1263_2557,MF0010_2558,2015-01-14,2015-07-23,กองทุนเปิดเค เอ็นแฮนซท์ ตราสารหนี้ 6 เดือน G,K Enhanced Fixed Income 6 Months G Fund,KEFI6MG,LI,C0000000021,-,2,2023-09-06T05:04:08

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1999 rows x 0 columns]

In [182]:
temp_unique_id = unique_id

In [184]:
temp_unique_id

['C0000000021',
 'C0000000023',
 'C0000000124',
 'C0000000182',
 'C0000000239',
 'C0000000290',
 'C0000000324',
 'C0000000329',
 'C0000000460',
 'C0000000569',
 'C0000000623',
 'C0000000709',
 'C0000000714',
 'C0000003575',
 'C0000004884',
 'C0000005022',
 'C0000005025',
 'C0000005531',
 'C0000006099',
 'C0000006122',
 'C0000006185',
 'C0000006466',
 'C0000006646',
 'C0000021747',
 'C0000024008',
 'C0000028866',
 'C0000031161',
 'C0000033081',
 'C0000033452']